<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-HILFICR" failures="1" tests="3" name="Test" time="29.405" errors="0" timestamp="2022-12-21T14:47:02 IST">
  <testcase classname="TestCases.LoginTestCase" name="verifyLogin" time="1.659"/>
  <testcase classname="TestCases.MyAccountTestCase" name="EditAccountDetails" time="6.674">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Success: Your account has successfully updated.] but found [Success: Your account has been successfully updated.]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Success: Your account has successfully updated.] but found [Success: Your account has been successfully updated.]
at Resources.CommonMethods.Assertion(CommonMethods.java:13)
at TestCases.MyAccountTestCase.EditAccountDetails(MyAccountTestCase.java:19)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- EditAccountDetails -->
  <testcase classname="TestCases.VerifyCartValue" name="VerifyCartVal" time="0.643"/>
  <testcase classname="Resources.BaseClass" name="@BeforeTest launch" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeTest launch -->
  <testcase classname="Resources.BaseClass" name="@BeforeTest launch" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeTest launch -->
</testsuite> <!-- Test -->
